### ISSUE TITLE
Requirements for Development

### ISSUE THREAD

**Issue by adam-kuhn** [eezstreet/OpenD2#24]
At the moment I see that you need a copy of D2 to compile the current build. I currently don't own a copy of D2 and won't know when I will. Is there a point sometime soon where you won't need a copy of D2 to contribute?

I also on a Mac, could you add instructions on how to compile on Mac?

It would also be great to have an active back log, so we can see what needs to be worked on.

I'm not an experienced game developer but I'd like to help out if/when I can, for the love of D2

**Comment by NorthernLight1** [comment]
I would recommend that you start off by installing Visual Studio Code and then follow the direction in the link below for setting a C++ compiler and debugger in VSC. 

https://devblogs.microsoft.com/cppblog/building-your-c-application-with-visual-studio-code/

You will need a copy of Diablo 2 to run the game right now, but I don't think you need it in order to compile it.
